services:
  orchestrator:
    build: .
    # image tag is optional for local dev; keep a simple local name if you want
    image: orchestrator:dev
    env_file: .env
    ports:
      - "8080:3000"          # app listens on 3000; map host 8080 -> 3000
    command: ["node", "dist/app.js"]
    restart: unless-stopped

  api:
    build: .
    image: orchestrator:dev  # reuse the same built image
    env_file: .env
    ports:
      - "8081:3000"          # expose API on a different host port
    command: ["node", "dist/api.js"]
    restart: unless-stopped

