version: "3.9"
services:
  orchestrator:
    build: .
    image: ghcr.io/OWNER/REPO:dev
    env_file: .env
    ports:
      - "8080:8080"
    command: ["node", "dist/app.js"]
    restart: unless-stopped

  api:
    build: .
    image: ghcr.io/OWNER/REPO:dev
    env_file: .env
    ports:
      - "8081:8080"
    command: ["node", "dist/api.js"]
    restart: unless-stopped

