name: Build & Push Docker Image

on:
  push:
    branches: [ "main" ]   # 每次推 main 分支就构建并推送
  workflow_dispatch:       # 允许手动触发

permissions:
  contents: read
  packages: write          # 允许写 GHCR（关键）

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}   # e.g. owner/repo
  SHA: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 规范化镜像名为小写（GHCR 要求）
      - name: Lowercase & compose image id
        id: lc
        run: |
          IMAGE_ID="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          echo "image_id=$(echo "$IMAGE_ID" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.lc.outputs.image_id }}:latest
            ${{ steps.lc.outputs.image_id }}:${{ env.SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

